name: to_do_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  dart_mappable: ^4.5.0
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  intl: ^0.20.2
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/home/
    - assets/images/intro/