name: to_do_app_development
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  table_calendar: ^3.0.8
  flutter_time_picker_spinner: ^2.0.0
  calendar_view: ^1.0.5
<<<<<<< HEAD
  image_picker: ^1.0.4
  easy_localization: ^3.0.5
  rxdart: ^0.27.7
=======
>>>>>>> cdd6b355a4275f9c1fc6085dd11dcb1a41ec23ed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
<<<<<<< HEAD
   - translations/
   
=======
>>>>>>> cdd6b355a4275f9c1fc6085dd11dcb1a41ec23ed
