name: todo_list
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2



dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1



  syncfusion_flutter_datepicker: ^29.2.7

  time_picker_spinner: ^1.0.2
  font_awesome_flutter: ^10.8.0
  lucide_icons: ^0.257.0



  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1

  easy_localization: ^3.0.7

  smooth_page_indicator: ^1.2.1
  dart_mappable: ^4.5.0

  intl: ^0.20.2
  get_it: ^8.0.3
  table_calendar: ^3.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0

  
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - .env


 