// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:uuid/uuid.dart';

// Will be generated by dart_mappable
part  'task_model.mapper.dart';

@MappableClass()
class TaskModel with TaskModelMappable  {

  TaskModel({this.userName, required this.taskName, required this.categoryName, required this.deadLine, required this.priorityTask ,required this.isCompleted}){
    id = Uuid().v4();
  }

  late final String id;

  @MappableField(key: 'user_name')
  String? userName;

  @MappableField(key: 'task_name')
  String taskName;

  @MappableField(key: 'category_name')
  String categoryName;

  @MappableField(key: 'dead_line')
  DateTime deadLine;

  @MappableField(key: 'priority_task')
  String priorityTask;

  @MappableField(key: 'is_completed')
  bool isCompleted;
  
  
  Map<String, String> convertToMap() {
    return {
      "id": id,
      "user_name": userName ?? "Unknown",
      "task_name": taskName,
      "category_name": categoryName,
      "dead_line": deadLine.toString(),
      "priority_task": priorityTask,
      "is_completed": isCompleted.toString(),
    };
  }
}