// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'task_model.mapper.dart';

@MappableClass()
class TaskModel with TaskModelMappable {
  TaskModel({ required this.userId ,required this.taskName, required this.isCompleted});

  @MappableField(key: 'user_id')
  String userId;

  @MappableField(key: 'task_name')
  String taskName;

  @MappableField(key: 'is_completed')
  bool isCompleted;
}