import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'task_model.mapper.dart';

@MappableClass()
class TaskModel with TaskModelMappable {
  final int? id;
  final String title;
  final String description;
  // @MappableField(hook: DateTimeHook())
  final DateTime dateTime;
  final int priority;
  final String userId;

  TaskModel({
    required this.userId,
    this.id,
    required this.title,
    required this.description,
    required this.dateTime,
    required this.priority,
  });

  Map<String, dynamic> toMap() {
    return {
      'title': title,
      'description': description,
      'date_time': dateTime.toIso8601String(),
      'user_id': userId,
      'priority': priority,
    };
  }
}
