import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'todo_model.mapper.dart';

@MappableClass()
class ToDoModel with ToDoModelMappable {
  ToDoModel({
    this.id,
    required this.userId,
    required this.task,
    required this.description,
    required this.dueDate,
    required this.isDone,
    required this.category,
    required this.priority,
  });
  String? id;
  @MappableField(key: 'user_id')
  final String userId;
  String task;
  String description;
  @MappableField(key: 'due_date')
  String dueDate;
  @MappableField(key: 'is_done')
  bool isDone;
  String? category;
  int? priority;
}
