import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'user_model.mapper.dart';

@MappableClass()
class UserModel with UserModelMappable {
  final String userName;
  final String passWord;
  final String confirmPass;

  UserModel({
    required this.userName,
    required this.passWord,
    required this.confirmPass,
  });
}
