name: to_do_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  supabase_flutter: ^1.10.22
  easy_localization: ^3.0.2
  google_fonts: ^6.1.0
  uuid: ^3.0.7
  equatable: ^2.0.5
  flutter_datetime_picker_plus: ^2.0.1
  flutter_time_picker_spinner: ^2.0.0
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/